version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    image: sushakov/dpkg-status-webapp-server
    restart: unless-stopped
    command: yarn start-server
    volumes:
      - yarn_cache:/yarn
    networks:
      - gateway
  client:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    image: sushakov/dpkg-status-webapp-client
    restart: unless-stopped
    volumes:
      - yarn_cache:/yarn
    depends_on:
      - server
    ports:
      - "80:80"
    command: nginx -g 'daemon off;'
    networks:
      - gateway

volumes:
  yarn_cache:

networks:
  gateway: {}
